### ISSUE TITLE
Freeing a node removes the bank even if other nodes use it

### ISSUE THREAD

**Issue by taikuukaits** [hugemenace/resonate#12]
Hello,

I like the plugin and am trying to use it but am having a problem once a scene with a sound bank is freed.

I have a scene with a sound bank where the scene is instantiated and freed at run time. For example it might be an 'enemy' and in that enemy scene is a Sound Bank. The enemy itself plays events 'enemy_hit'. And I instantiate multiple enemies. This works fine until you free one of those enemies, then the bank gets removed and the second enemy can no longer play sounds from the bank. 

I have created a small repro, a main scene with:
```
extends Node2D
var scene = preload("res://node_with_bank.tscn")

func _ready():
	var last_node
	
	while true:
		last_node = scene.instantiate()
		add_child(last_node)
		await get_tree().create_timer(1).timeout
		last_node.queue_free()
```
And an instantiated scene
```
extends Node
func _ready():
	await get_tree().create_timer(1).timeout
	
	while true:
		SoundManager.play("example_bank", "example_event")
		await get_tree().create_timer(1).timeout
```
With the appropriate sound bank.
![image](https://github.com/hugemenace/resonate/assets/7539378/48da0319-b56a-4aab-a905-566a2c5d31e4)

But after running for more than a second you see errors:
![image](https://github.com/hugemenace/resonate/assets/7539378/a5b2a897-ee7a-428d-bfab-4733930ab76a)

I am wondering if this is not the expected setup for this scenario? Should I have the sound bank in the main scene? Can there only be one instance with each sound bank?

Using `version="2.3.2"`
Zip with repro: [resonate_example.zip](https://github.com/hugemenace/resonate/files/14290395/resonate_example.zip)

**Comment by tristan-hm** [comment]
Thank you for providing a thorough report & repro!

We didn't consider this edge case, but luckily, it's easy to fix. To be clear, you should be able to co-locate your sound/music banks with the scenes that utilise them - that's intended, so the current behaviour isn't correct. However, as you suggested, you could immediately solve this by moving your sound bank higher up the scene tree (to the root of your level, for example).

I'll work on a fix for this issue and push it out in the next release, which should be published by the end of the week.

**Comment by taikuukaits** [comment]
Just wanted to say finally got a chance to update and looks like the issue is fixed! Thank you very much for the quick fix!
