### ISSUE TITLE
Getting the length of a stem's audio stream

### ISSUE THREAD

**Issue by oneirophon** [hugemenace/resonate#17]
Hello! I'm trying to get my music tracks to loop by crossfading with themselves, but there doesn't seem to be any built-in way to do this with Resonate. I'd implement that functionality myself by getting the length of the audio stream attached to the stem for the current track (I'm only using one stem per track) and starting the crossfade when the playback position reaches the length of the track minus an offset, but I can't find a way to access the audios stream associated with a stem.

**Comment by tristan-hm** [comment]
Hi there! So, there are two options here:

**Option 1:** If you want your music tracks to repeat/loop automatically, ensure that the audio streams (stems) are set to loop in the import settings. You can do this by selecting an audio file in the FileSystem window and setting the respective loop options (different for each file type: wav, mp3, ogg, etc.) in the import settings panel (usually sitting next to the scene tab). Note that this won't blend the end and start of a stem with a crossfade, so you either want to ensure that your stems are loopable or add a slight fade in and out to the audio file itself.

Option 2: If the above differs from what you're after, I can look at exposing the underlying audio stream/player associated with the music track. However, given that the MusicManager creates a single audio stream player per track and plays each stem polyphonically, it may not give you the information you're after. So, enabling auto loop & crossfading on a single track may require a little more work - but I'd be happy to look into it.

**Comment by oneirophon** [comment]
Currently, I've got the stems set to loop, but it sounds a bit jarring without the crossfade effect I'm looking for. It would be awesome if you could look into enabling single-track crossfading!

**Comment by tristan-hm** [comment]
No worries. Leave it with me. I'll look into it and try to push that feature out with the next release.

**Comment by tristan-hm** [comment]
Hey! Just letting you know this feature has just been pushed out with **v2.4.0**.

To use it, set `p_crossfade_time` and `p_auto_loop` on the MusicManager's play method, for example:

```GDScript
MusicManager.play("main", "track", 5.0, true)
```

The above will automatically loop (replay) "track" when it reaches the end, with a 5.0-second crossfade.
