### ISSUE TITLE
Web Export MusicManager Not Stopping Music

### ISSUE THREAD

**Issue by TypicalFooBar** [hugemenace/resonate#21]
This plugin works as expected when in the editor and on Windows. However, when running in a web browser, the MusicManager never actually stops playing music even when MusicManager.stop() is called. I have also seen that the tween that is used does not lower the volume when phasing out the music. The end result is that multiple music tracks end up playing on top of each other, since previous ones never stopped.

The same exact code works perfectly on Windows.

**Comment by tristan-hm** [comment]
Sorry for the late response. I'm glad to hear you got it working! We'll look at adding a note about it to the docs.
